version: "3.7"

services:
  stakeholders:
    build:
      context: ./Stakeholders
      dockerfile: Dockerfile
    image: stakeholders_web_server
    container_name: stakeholders_server
    restart: always
    networks:
      - servers
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - NEO4J_DB=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=stakeholders


  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    restart: always
    networks:
      - servers
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/stakeholders
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:

networks:
  servers:
    name: servers
    driver: bridge
