version: "3.7"

services:
  # Gateway servis
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: gateway_web_server
    container_name: gateway_server
    restart: always
    networks:
      - servers
    ports:
      - "8080:8080"
    depends_on:
      - stakeholders
      - blog-service
      - tours-service
    environment:
      - STAKEHOLDERS_SERVICE_ADDRESS=stakeholders:8000
      - BLOG_SERVICE_ADDRESS=blog-service:8082
      - TOURS_SERVICE_ADDRESS=tours-service:8084
      - GATEWAY_ADDRESS=:8080

  # Stakeholders servis (gRPC server)
  stakeholders:
    build:
      context: ./Stakeholders
      dockerfile: Dockerfile
    image: stakeholders_web_server
    container_name: stakeholders_server
    restart: always
    networks:
      - servers
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_DB=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=stakeholders

  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    restart: always
    networks:
      - servers
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/stakeholders
    volumes:
      - ./Stakeholders/uploads:/app/uploads

  # Blog servis
  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    image: blogs_web_server
    container_name: blog_server
    restart: always
    networks:
      - servers
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - BLOG_SERVICE_ADDRESS=:8082
      - MONGODB_URI=mongodb://app-mongo:27017/blogdb
    volumes:
      - ./blog-service/uploads:/app/uploads
  
  # Tours servis
  tours-service:
    build:
      context: ./Tours
      dockerfile: Dockerfile
    image: tours_web_server
    container_name: tours_server
    restart: always
    networks:
      - servers
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://app-mongo:27017/toursdb
    volumes:
      - ./Tours/uploads:/app/uploads

  # MongoDB (koristi se i za blog i za tours)
  mongo:
    image: mongo:6.0.5
    platform: linux/amd64
    container_name: app-mongo
    restart: always
    networks:
      - servers
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Mongo-Express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://app-mongo:27017/
    networks:
      - servers

volumes:
  neo4j_data:
  mongo_data:

networks:
  servers:
    name: servers
    driver: bridge
